# Generated by Django 4.2.3 on 2023-07-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ec', models.IntegerField()),
                ('ph', models.DecimalField(decimal_places=2, max_digits=6)),
                ('water_temp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('do', models.DecimalField(decimal_places=2, max_digits=6)),
                ('co2', models.IntegerField()),
                ('kwh', models.IntegerField(default=0)),
            ],
        ),
    ]
