# Generated by Django 4.2.3 on 2023-08-15 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_alter_sensorrecord_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorrecord",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 15, 20, 49, 2, 93201)
            ),
        ),
    ]
