# Generated by Django 4.2.3 on 2023-08-01 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_growlightmodel_first_cycle_end_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DosingSwtiches',
            new_name='DosingSwitches',
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='first_cycle_end',
            field=models.TimeField(default=datetime.time(19, 56, 34, 101834)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='first_cycle_start',
            field=models.TimeField(default=datetime.time(19, 56, 34, 101821)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='second_cycle_end',
            field=models.TimeField(default=datetime.time(19, 56, 34, 101841)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='second_cycle_start',
            field=models.TimeField(default=datetime.time(19, 56, 34, 101838)),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='watering_time',
            field=models.TimeField(default=datetime.time(19, 56, 34, 102231)),
        ),
    ]
