# Generated by Django 4.2.3 on 2023-08-01 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_rename_dosingswtiches_dosingswitches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringschedule',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='first_cycle_end',
            field=models.TimeField(default=datetime.time(20, 41, 23, 883226)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='first_cycle_start',
            field=models.TimeField(default=datetime.time(20, 41, 23, 883217)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='second_cycle_end',
            field=models.TimeField(default=datetime.time(20, 41, 23, 883232)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='second_cycle_start',
            field=models.TimeField(default=datetime.time(20, 41, 23, 883229)),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='watering_time',
            field=models.TimeField(default=datetime.time(20, 41, 23, 883611)),
        ),
    ]
