# Generated by Django 4.2.3 on 2023-08-01 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_wateringschedule_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosingtargetandtolerance',
            name='ph_target',
            field=models.FloatField(default=6.0),
        ),
        migrations.AlterField(
            model_name='dosingtargetandtolerance',
            name='ph_tolerance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='first_cycle_end',
            field=models.TimeField(default=datetime.time(20, 55, 46, 68269)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='first_cycle_start',
            field=models.TimeField(default=datetime.time(20, 55, 46, 68260)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='second_cycle_end',
            field=models.TimeField(default=datetime.time(20, 55, 46, 68275)),
        ),
        migrations.AlterField(
            model_name='growlightmodel',
            name='second_cycle_start',
            field=models.TimeField(default=datetime.time(20, 55, 46, 68272)),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='watering_time',
            field=models.TimeField(default=datetime.time(20, 55, 46, 68640)),
        ),
    ]
