# Generated by Django 4.2.3 on 2023-08-03 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_growlightsmodel_delete_growlightmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingmode',
            old_name='growlight_mode',
            new_name='growlights_mode',
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='first_cycle_end',
            field=models.TimeField(default=datetime.time(11, 12, 45, 414432)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='first_cycle_start',
            field=models.TimeField(default=datetime.time(11, 12, 45, 414420)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_end',
            field=models.TimeField(default=datetime.time(11, 12, 45, 414438)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_start',
            field=models.TimeField(default=datetime.time(11, 12, 45, 414435)),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='watering_time',
            field=models.TimeField(default=datetime.time(11, 12, 45, 414850)),
        ),
    ]
