# Generated by Django 4.2.3 on 2023-08-06 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0009_rename_growlight_mode_settingmode_growlights_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_end",
            field=models.TimeField(default=datetime.time(12, 59, 3, 63251)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_start",
            field=models.TimeField(default=datetime.time(12, 59, 3, 63241)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_end",
            field=models.TimeField(default=datetime.time(12, 59, 3, 63257)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_start",
            field=models.TimeField(default=datetime.time(12, 59, 3, 63254)),
        ),
        migrations.AlterField(
            model_name="wateringschedule",
            name="watering_time",
            field=models.TimeField(default=datetime.time(12, 59, 3, 63613)),
        ),
    ]
