# Generated by Django 4.2.3 on 2023-08-07 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0011_alter_growlightsmodel_first_cycle_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_end",
            field=models.TimeField(default=datetime.time(9, 55, 46, 892697)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_start",
            field=models.TimeField(default=datetime.time(9, 55, 46, 892688)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_end",
            field=models.TimeField(default=datetime.time(9, 55, 46, 892704)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_start",
            field=models.TimeField(default=datetime.time(9, 55, 46, 892701)),
        ),
        migrations.AlterField(
            model_name="wateringschedule",
            name="watering_time",
            field=models.TimeField(default=datetime.time(9, 55, 46, 893069)),
        ),
    ]
