# Generated by Django 4.2.3 on 2023-08-07 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0014_alter_growlightsmodel_first_cycle_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_end",
            field=models.TimeField(default=datetime.time(10, 11, 15, 733300)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_start",
            field=models.TimeField(default=datetime.time(10, 11, 15, 733293)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_end",
            field=models.TimeField(default=datetime.time(10, 11, 15, 733305)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_start",
            field=models.TimeField(default=datetime.time(10, 11, 15, 733302)),
        ),
        migrations.AlterField(
            model_name="wateringschedule",
            name="watering_time",
            field=models.TimeField(default=datetime.time(10, 11, 15, 733663)),
        ),
    ]
