# Generated by Django 4.2.3 on 2023-08-15 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0015_alter_growlightsmodel_first_cycle_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growlightsmodel',
            name='first_cycle_end',
            field=models.TimeField(default=datetime.time(17, 47, 5, 342189)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='first_cycle_start',
            field=models.TimeField(default=datetime.time(17, 47, 5, 342164)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_end',
            field=models.TimeField(default=datetime.time(17, 47, 5, 342209)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_start',
            field=models.TimeField(default=datetime.time(17, 47, 5, 342200)),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='watering_time',
            field=models.TimeField(default=datetime.time(17, 47, 5, 343987)),
        ),
    ]
