<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-15 10:47
=======
# Generated by Django 4.2.3 on 2023-08-15 13:49
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('setting', '0015_alter_growlightsmodel_first_cycle_end_and_more'),
=======
    dependencies = [
        ("setting", "0015_alter_growlightsmodel_first_cycle_end_and_more"),
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='growlightsmodel',
            name='first_cycle_end',
            field=models.TimeField(default=datetime.time(17, 47, 5, 342189)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='first_cycle_start',
            field=models.TimeField(default=datetime.time(17, 47, 5, 342164)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_end',
            field=models.TimeField(default=datetime.time(17, 47, 5, 342209)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_start',
            field=models.TimeField(default=datetime.time(17, 47, 5, 342200)),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='watering_time',
            field=models.TimeField(default=datetime.time(17, 47, 5, 343987)),
=======
            model_name="growlightsmodel",
            name="first_cycle_end",
            field=models.TimeField(default=datetime.time(20, 49, 2, 93672)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_start",
            field=models.TimeField(default=datetime.time(20, 49, 2, 93665)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_end",
            field=models.TimeField(default=datetime.time(20, 49, 2, 93678)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_start",
            field=models.TimeField(default=datetime.time(20, 49, 2, 93675)),
        ),
        migrations.AlterField(
            model_name="wateringschedule",
            name="watering_time",
            field=models.TimeField(default=datetime.time(20, 49, 2, 94036)),
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63
        ),
    ]
