<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-15 10:47
=======
# Generated by Django 4.2.3 on 2023-08-15 13:52
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('setting', '0016_alter_growlightsmodel_first_cycle_end_and_more'),
=======
    dependencies = [
        ("setting", "0016_alter_growlightsmodel_first_cycle_end_and_more"),
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='growlightsmodel',
            name='first_cycle_end',
            field=models.TimeField(default=datetime.time(17, 47, 43, 558493)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='first_cycle_start',
            field=models.TimeField(default=datetime.time(17, 47, 43, 558468)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_end',
            field=models.TimeField(default=datetime.time(17, 47, 43, 558512)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_start',
            field=models.TimeField(default=datetime.time(17, 47, 43, 558503)),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='watering_time',
            field=models.TimeField(default=datetime.time(17, 47, 43, 560203)),
=======
            model_name="growlightsmodel",
            name="first_cycle_end",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824030)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_start",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824019)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_end",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824037)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_start",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824034)),
        ),
        migrations.AlterField(
            model_name="wateringschedule",
            name="watering_time",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824462)),
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63
        ),
    ]
