# Generated by Django 4.2.3 on 2023-08-15 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0016_alter_growlightsmodel_first_cycle_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_end",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824030)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_start",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824019)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_end",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824037)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_start",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824034)),
        ),
        migrations.AlterField(
            model_name="wateringschedule",
            name="watering_time",
            field=models.TimeField(default=datetime.time(20, 52, 21, 824462)),
        ),
    ]
