<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-15 10:47
=======
# Generated by Django 4.2.3 on 2023-08-15 21:07
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    dependencies = [
        ('setting', '0017_alter_growlightsmodel_first_cycle_end_and_more'),
=======
    dependencies = [
        ("setting", "0017_alter_growlightsmodel_first_cycle_end_and_more"),
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='growlightsmodel',
            name='first_cycle_end',
            field=models.TimeField(default=datetime.time(17, 47, 57, 315243)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='first_cycle_start',
            field=models.TimeField(default=datetime.time(17, 47, 57, 315219)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_end',
            field=models.TimeField(default=datetime.time(17, 47, 57, 315262)),
        ),
        migrations.AlterField(
            model_name='growlightsmodel',
            name='second_cycle_start',
            field=models.TimeField(default=datetime.time(17, 47, 57, 315253)),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='watering_time',
            field=models.TimeField(default=datetime.time(17, 47, 57, 316957)),
=======
            model_name="growlightsmodel",
            name="first_cycle_end",
            field=models.TimeField(default=datetime.time(21, 7, 21, 914726)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="first_cycle_start",
            field=models.TimeField(default=datetime.time(21, 7, 21, 914717)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_end",
            field=models.TimeField(default=datetime.time(21, 7, 21, 914733)),
        ),
        migrations.AlterField(
            model_name="growlightsmodel",
            name="second_cycle_start",
            field=models.TimeField(default=datetime.time(21, 7, 21, 914729)),
        ),
        migrations.AlterField(
            model_name="wateringschedule",
            name="watering_time",
            field=models.TimeField(default=datetime.time(21, 7, 21, 915091)),
>>>>>>> 30a9380c67f27c4e17fc2c230ccc709d6e7c1d63
        ),
    ]
